image: node:14.4.0

stages:
  - unit_tests
  - build


before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - yarn install

unit_tests:
  dependencies: []
  stage: unit_tests
  artifacts:
  script:
    - yarn lint
  tags:
    - docker

build:
  dependencies: []
  stage: unit_tests
  artifacts:
  script:
    - yarn build
  tags:
    - docker
