image: node:14.4.0

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/


stages:
  - setup
  - tests
  - build


before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

install_yarn:
  dependencies: []
  stage: setup
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour
  script:
    - yarn install
  tags:
    - docker
 

lint:
  dependencies: [install_yarn]
  stage: tests
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour
  script:
    - yarn lint
  tags:
    - docker

build:
  dependencies: [lint]
  stage: build
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour
   
  script:
    - yarn build
  tags:
    - docker
